Fix/subactinide
njoy/NJOY2016 pull request #242
Opened 2022-05-03 20:37 UTC by whaeck

Fixes issue #241 

Contrary to what I said before, I propose merging it into develop and release the fix as a part of NJOY2016.67 instead of it being a single update. Some of the JENDL5 fixes broke NJOY as well and we did not release those fixes either.

2022-05-04 22:23 UTC, nathangibson14 requested changes
Maybe I'm blind, but I don't see the change that fixes this.  I know it's just a one-liner.  Can you point it out to me for my benefit so I don't lose hair searching for it?

2022-05-04 22:23 UTC, nathangibson14 commented on tests/72/input.txt
> + moder
Why is this file here?  Looks like a duplicate of `input`, maybe you forgot to delete it.

2022-05-04 22:23 UTC, nathangibson14 commented on src/groupr.f90
> +         egn(ig)=eg33(ig)
These don't look like compiler warnings but real bugs.  Were we really pointing to the wrong group structure for setting these?  I don't see discussion of this in the issue or the PR.  What's the context?

2022-05-05 03:56 UTC, whaeck commented on tests/72/input.txt
> + moder
This is a duplicate that I had to create to make the issue, I removed it.

2022-05-05 03:57 UTC, whaeck commented on src/groupr.f90
> +         egn(ig)=eg33(ig)
The compiler warnings actually told me that eg33 was never used - which is not what we wanted. I must have made this mistake a long time ago and nobody told me ...

2022-05-05 03:59 UTC, whaeck commented
> Maybe I'm blind, but I don't see the change that fixes this. I know it's just a one-liner. Can you point it out to me for my benefit so I don't lose hair searching for it?

the two lines that say ```izar=-1``` fix the problem.

2022-05-05 20:51 UTC, nathangibson14 approved these changes
Hopefully you can fix the release notes without me needing to reapprove, but if not I'll reapprove quickly.

2022-05-05 20:51 UTC, nathangibson14 commented on ReleaseNotes.md
> +  - properly set the za in the case of sub-actinide fission (MF10 MT18 data) when using MF10 automated processing in GROUPR (issue #241)
Fixing the group structures should be in the release notes.

2022-05-05 21:22 UTC, whaeck commented on ReleaseNotes.md
> +  - properly set the za in the case of sub-actinide fission (MF10 MT18 data) when using MF10 automated processing in GROUPR (issue #241)
It'll make the review stale if I push but don't worry about that

2022-05-06 14:31 UTC, merged