Fix wrong memory addresses due to not accounted GROUPR offset
njoy/NJOY2016 pull request #262
Opened 2022-09-15 08:10 UTC by kernie

GROUPR writes gendf data in a compact way and let us know, what the offset is.

The dlayxs part of CCCR loops over the full energy group range in container variable `a` where it should loop only until the offset. Thereby, on chance uninitialized or invalid memory may be addressed and may lead at best to a crash or simply runs without error but resulting in values like 1.E+44 for delayed spectra.

This commit introduces the offset and corrects 2 loops. Moreover,  a check is introduced if the requested memory fits into the `a` variable. The `a` size variable `isiza` was moved to a parameter statement and renamed to account for 4 byte and 8 byte equivalence'd variables.

2022-09-15 08:52 UTC, kernie commented
To see the erroneous bevavior, one can take [input.cccr_u232_361.txt](https://github.com/njoy/NJOY2016/files/9573570/input.cccr_u232_361.txt) with ENDF6 data of U-232. It uses the SHEM-361 group structure.

2022-09-15 16:35 UTC, whaeck requested changes
Just a few minor questions that we should address before approving this.

I have asked @nathangibson14 to have a look if he has some time - but I think these changes are pretty straight forward.

2022-09-15 17:16 UTC, kernie commented on ReleaseNotes.md
> +This constitutes a major update of NJOY to aommodate the latest IAEA photonuclear data library (which uses non-isotropic photon distributions) and the mixed mode elastic scattering ENDF format (adopt
Yes, looks like ghost-typing...

2022-09-15 17:44 UTC, kernie commented on src/ccccr.f90
> +         ig1=nint(e(3))-1
I think the 1 is save. I'm not aware of a higher energy limit for fission in general (but this is out of my theoretical knowledge).

If I understand GROUPR correctly the first position in the delayed fission matrix holds the decay constant of the precursor family (GROUPR.f90:720). That is read before. And then we need to subtract 1 to get the real offset. I don't know whether it is the ideal place to do so, but at some point this is necessary.

2022-09-15 17:44 UTC, kernie commented on tests/77/input
> + 'pendf tape for  U 232 from jeff331'/
true

2022-09-15 17:56 UTC, kernie commented on tests/77/input
> + 25 00  00  30
I'll check that

2022-09-16 09:31 UTC, kernie commented on tests/77/input
> + 25 00  00  30
I removed test 77, since you are right. Test 76 covers it.

2022-09-16 15:55 UTC, whaeck approved these changes
I think this is good to go. I'm waiting for some feedback from @nathangibson14 before I merge but I think we won't need more changes here.

I did verify the specs for the delayed neutron data in the GENDF file and that -1 does indeed need to be taken into account. Putting the comment there makes it easier to understand as well.

2022-09-16 16:34 UTC, merged