Fixed ERRORR LRF7 segfault.
njoy/NJOY2016 pull request #279
Opened 2023-02-06 22:31 UTC by nathangibson14

This adds a simple check for whether MF32 is present before adding its contribution to computed covariances.  This only affects LRF=7 evaluations, such as Fe-54 in ENDF/B-VIII.0.

2023-02-06 23:06 UTC, whaeck requested changes

2023-02-06 23:06 UTC, whaeck commented on src/errorr.f90
> -   if (mfcov.ne.34.and.mfcov.ne.35) then
Why not just check for mfcov==33 and mf32 present?

i.e. : if (mfcov.eq.33.and.mf32.ne.0) then

because MF33 is the only one to which we need to add MF32 if it is present.

2023-02-06 23:35 UTC, nathangibson14 commented on src/errorr.f90
> -   if (mfcov.ne.34.and.mfcov.ne.35) then
For an LRF=7 evaluation without MF32 but with MF31, this fix does work.  But now I'm a bit worried about a case where LRF=7 is used *with* MF32.  I'm going to try to figure out what happens in that case.

That said, it's a moot point, as I definitely like checking for 33 better than checking for not everything else.

2023-02-06 23:46 UTC, nathangibson14 commented on src/errorr.f90
> -   if (mfcov.ne.34.and.mfcov.ne.35) then
I'm fairly confident this makes no difference, but I just updated to your recommendation.  Definitely cleaner code this way.

2023-02-07 15:43 UTC, whaeck approved these changes

2023-02-07 15:43 UTC, merged